const PDFDocument = require('pdfkit');
const https = require('https');
const http = require('http');

/**
 * Shared helpers for PDF generation
 */
const formatPrice = (paise) => {
  if (paise == null) return '₹0.00';
  return `₹${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const formatShortDate = (d) => {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
};

/**
 * Add standard header with company info and optional logo
 */
const addHeader = (doc, company, title) => {
  doc.fontSize(16).fillColor('#1e293b').font('Helvetica-Bold')
    .text('StockMate Pro', 50, 40);
  doc.fontSize(8).fillColor('#64748b').font('Helvetica')
    .text('Inventory Management System', 50, 60);
  doc.fontSize(11).fillColor('#334155').font('Helvetica-Bold')
    .text(title || 'Document', 50, 85);
  doc.moveTo(50, 105).lineTo(doc.page.width - 50, 105).strokeColor('#e2e8f0').lineWidth(1).stroke();
  return doc;
};

/**
 * Add standard footer
 */
const addFooter = (doc) => {
  const footerY = doc.page.height - 50;
  doc.fontSize(8).fillColor('#94a3b8').font('Helvetica')
    .text(
      `Generated by StockMate Pro | ${new Date().toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}`,
      50, footerY,
      { align: 'center', width: doc.page.width - 100 }
    );
  return doc;
};

/**
 * Generate a purchase order PDF as a Buffer
 * @param {Object} purchase - Full purchase object with items, supplier, branch, user
 * @param {Object} [company] - Optional company profile with name, address, phone, email, gstNumber, logoUrl, footerText
 * @returns {Promise<Buffer>}
 */
const generatePOPDF = async (purchase, company = null) => {
  const p = purchase;
  const c = company;

  // Fetch logo upfront if available
  let logoBuffer = null;
  if (c?.logoUrl) {
    try {
      const protocol = c.logoUrl.startsWith('https') ? https : http;
      logoBuffer = await new Promise((resolve, reject) => {
        protocol.get(c.logoUrl, (res) => {
          const chunks = [];
          res.on('data', (chunk) => chunks.push(chunk));
          res.on('end', () => resolve(Buffer.concat(chunks)));
          res.on('error', reject);
        }).on('error', reject);
      });
    } catch (e) {
      // Logo fetch failed, continue without logo
    }
  }

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
        info: {
          Title: `Purchase Order - ${p.poNumber}`,
          Author: c?.companyName || 'StockMate Pro',
          Subject: `PO #${p.poNumber}`,
        },
      });

      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100; // with margins
      const primaryColor = '#2563eb';
      const grayColor = '#64748b';
      const lightGray = '#f1f5f9';
      const borderColor = '#e2e8f0';

      // ── Helper functions ──
      const formatPrice = (paise) => {
        if (paise == null) return '₹0.00';
        return `₹${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
      };

      const formatShortDate = (d) => {
        if (!d) return '—';
        return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
      };

      // ── HEADER: Company & PO Info ──
      // Company name (use company profile if available, fall back to branch)
      const companyName = c?.companyName || p.branch?.name || 'StockMate Pro';

      // Company logo (if fetched successfully)
      let headerX = 50;
      let headerNameX = 50;
      if (logoBuffer) {
        doc.image(logoBuffer, 50, 50, { width: 50, height: 50 });
        headerNameX = 115;
      }
      doc.fontSize(20).fillColor(primaryColor).font('Helvetica-Bold')
        .text(companyName, headerNameX, 50);

      // Company address / contact info
      const companyAddr = [
        c?.address || p.branch?.address,
        c?.phone || p.branch?.phone,
        (c?.gstNumber || p.branch?.gstNumber) ? `GST: ${c?.gstNumber || p.branch?.gstNumber}` : '',
      ].filter(Boolean).join('\n');
      if (companyAddr) {
        const addrY = logoBuffer ? 82 : 78;
        const addrX = logoBuffer ? headerNameX : 50;
        doc.fontSize(9).fillColor(grayColor).font('Helvetica')
          .text(companyAddr, addrX, addrY, { width: 250 });
      }

      // PO Number - Right aligned using calculated x
      const poNumberText = p.poNumber;
      doc.fontSize(22).fillColor('#1e293b').font('Helvetica-Bold')
        .text(poNumberText, 0, 50, { align: 'right', width: doc.page.width - 50 });

      // Status badge (simulated with colored text)
      const statusColors = {
        DRAFT: '#64748b', ORDERED: '#2563eb', PARTIAL: '#d97706',
        RECEIVED: '#059669', CANCELLED: '#94a3b8',
      };
      const statusColor = statusColors[p.status] || '#64748b';
      doc.fontSize(10).fillColor(statusColor).font('Helvetica-Bold')
        .text(p.status, 0, 76, { align: 'right', width: doc.page.width - 50 });

      // Date info right side
      doc.fontSize(9).fillColor(grayColor).font('Helvetica')
        .text(`Order Date: ${formatShortDate(p.orderDate)}`, 0, 92, { align: 'right', width: doc.page.width - 50 });
      if (p.expectedDate) {
        doc.text(`Expected: ${formatShortDate(p.expectedDate)}`, 0, 106, { align: 'right', width: doc.page.width - 50 });
      }

      // Divider
      doc.moveTo(50, 125).lineTo(doc.page.width - 50, 125).strokeColor(primaryColor).lineWidth(2).stroke();

      // ── INFO SECTION: Supplier & Payment ──
      const infoY = 140;

      // Supplier box
      doc.roundedRect(50, infoY, pageWidth / 2 - 12, 82, 6).fillColor('#f8fafc').fill()
        .roundedRect(50, infoY, pageWidth / 2 - 12, 82, 6).strokeColor(borderColor).lineWidth(1).stroke();

      doc.fontSize(9).fillColor(grayColor).font('Helvetica-Bold')
        .text('SUPPLIER', 64, infoY + 8);

      if (p.supplier) {
        doc.fontSize(10).fillColor('#334155').font('Helvetica-Bold')
          .text(p.supplier.name, 64, infoY + 24);
        const supplierInfo = [
          p.supplier.address,
          p.supplier.phone ? `Phone: ${p.supplier.phone}` : '',
          p.supplier.email ? `Email: ${p.supplier.email}` : '',
          p.supplier.gstNumber ? `GST: ${p.supplier.gstNumber}` : '',
        ].filter(Boolean).join('\n');
        doc.fontSize(9).fillColor('#475569').font('Helvetica')
          .text(supplierInfo, 64, infoY + 42, { width: pageWidth / 2 - 36 });
      } else {
        doc.fontSize(10).fillColor(grayColor).font('Helvetica').text('—', 64, infoY + 24);
      }

      // Payment box
      doc.roundedRect(50 + pageWidth / 2 + 12, infoY, pageWidth / 2 - 12, 82, 6).fillColor('#f8fafc').fill()
        .roundedRect(50 + pageWidth / 2 + 12, infoY, pageWidth / 2 - 12, 82, 6).strokeColor(borderColor).lineWidth(1).stroke();

      doc.fontSize(9).fillColor(grayColor).font('Helvetica-Bold')
        .text('PAYMENT', 64 + pageWidth / 2 + 12, infoY + 8);

      const payX = 64 + pageWidth / 2 + 12;
      doc.fontSize(9).fillColor('#475569').font('Helvetica')
        .text(`Status: ${p.paymentStatus}${p.paymentStatus === 'PAID' ? ' ✓' : ''}`, payX, infoY + 26)
        .text(`Paid: ${formatPrice(p.paidAmount)}`, payX, infoY + 40);

      if (p.balanceAmount > 0) {
        doc.fillColor('#d97706').text(`Balance: ${formatPrice(p.balanceAmount)}`, payX, infoY + 54);
      } else {
        doc.fillColor('#059669').text('Fully Paid', payX, infoY + 54);
      }

      doc.fillColor('#475569')
        .text(`Items: ${p.items?.length || 0}`, payX, infoY + 68);

      // ── ITEMS TABLE ──
      const tableTop = infoY + 100;
      const colWidths = [30, 170, 44, 50, 82, 44, 90];
      const headers = ['#', 'Item', 'Qty', 'Recv\'d', 'Rate', 'GST', 'Total'];

      // Table header bg
      doc.rect(50, tableTop, pageWidth, 24).fill(lightGray);

      // Header text
      let x = 50;
      doc.fontSize(8).fillColor(grayColor).font('Helvetica-Bold');
      headers.forEach((h, i) => {
        const align = i === 0 || i === 2 || i === 3 || i === 5 ? 'center' : i === 4 || i === 6 ? 'right' : 'left';
        doc.text(h, x, tableTop + 6, { width: colWidths[i], align, lineBreak: false });
        x += colWidths[i];
      });

      // Table rows
      let rowY = tableTop + 24;
      const items = p.items || [];

      items.forEach((item, idx) => {
        const gstPercent = parseInt((item.gstRate || 'RATE_18').replace('RATE_', ''));
        const lineTotal = item.unitPrice * item.quantity;
        const gstAmount = Math.round(lineTotal * gstPercent / 100);
        const total = lineTotal + gstAmount;
        const received = item.receivedQty || 0;

        // Row background (alternating)
        if (idx % 2 === 0) {
          doc.rect(50, rowY, pageWidth, 22).fill('#fafafa');
        }

        // Row bottom border
        doc.moveTo(50, rowY + 22).lineTo(doc.page.width - 50, rowY + 22).strokeColor(borderColor).lineWidth(0.5).stroke();

        // Row data
        const cells = [
          String(idx + 1),
          item.item?.name || 'Item',
          String(item.quantity),
          received > 0 ? String(received) : '—',
          formatPrice(item.unitPrice),
          `${gstPercent}%`,
          formatPrice(total),
        ];

        let cx = 50;
        doc.fontSize(9).fillColor('#334155').font('Helvetica');
        cells.forEach((cell, i) => {
          const align = i === 0 || i === 2 || i === 3 || i === 5 ? 'center' : i === 4 || i === 6 ? 'right' : 'left';
          const font = i === 6 ? 'Helvetica-Bold' : 'Helvetica';
          doc.font(font).text(cell, cx, rowY + 4, { width: colWidths[i], align, lineBreak: false });
          cx += colWidths[i];
        });

        // SKU under item name
        if (item.item?.sku) {
          doc.fontSize(7).fillColor(grayColor).font('Helvetica')
            .text(item.item.sku, 80, rowY + 12, { width: 140 });
        }

        rowY += 22;
      });

      // ── TOTALS ──
      const totalsX = doc.page.width - 50 - 240;
      const totalsY = rowY + 10;

      const totalsData = [
        { label: 'Subtotal', value: formatPrice(p.subtotal), color: '#334155', bold: false },
        ...(p.discountTotal > 0
          ? [{ label: 'Discount', value: `−${formatPrice(p.discountTotal)}`, color: '#dc2626', bold: false }]
          : []),
        { label: 'GST Total', value: formatPrice(p.gstTotal), color: '#334155', bold: false },
        { label: 'Grand Total', value: formatPrice(p.grandTotal), color: '#ffffff', bold: true, isGrand: true },
      ];

      if (p.balanceAmount > 0) {
        totalsData.push({ label: 'Balance Due', value: formatPrice(p.balanceAmount), color: '#d97706', bold: true });
      }

      totalsData.forEach((row) => {
        if (row.isGrand) {
          doc.rect(totalsX, totalsY, 240, 26).fill(primaryColor);
        }
        doc.fontSize(row.isGrand ? 11 : 9)
          .fillColor(row.color)
          .font(row.bold ? 'Helvetica-Bold' : 'Helvetica');
        doc.text(row.label, totalsX + 12, totalsY + (row.isGrand ? 6 : 3), { width: 120 });
        doc.text(row.value, totalsX + 132, totalsY + (row.isGrand ? 6 : 3), { width: 96, align: 'right' });
        if (!row.isGrand) {
          doc.moveTo(totalsX, totalsY + 20).lineTo(totalsX + 240, totalsY + 20).strokeColor(borderColor).lineWidth(0.5).stroke();
        }
      });

      // ── SUPPLIER INVOICE INFO ──
      let bottomY = totalsY + (totalsData.length * 22) + 20;

      if (p.supplierInvoice) {
        doc.fontSize(9).fillColor('#334155').font('Helvetica')
          .text(`Supplier Invoice: ${p.supplierInvoice}`, 50, bottomY);
        if (p.supplierInvDate) {
          doc.text(`Invoice Date: ${formatShortDate(p.supplierInvDate)}`, 50, bottomY + 14);
        }
        bottomY += 36;
      }

      // ── NOTES ──
      if (p.notes) {
        doc.roundedRect(50, bottomY, pageWidth, 50, 6).fillColor('#f8fafc').fill()
          .roundedRect(50, bottomY, pageWidth, 50, 6).strokeColor(borderColor).lineWidth(1).stroke();
        doc.fontSize(9).fillColor(grayColor).font('Helvetica-Bold')
          .text('NOTES', 64, bottomY + 8);
        doc.fontSize(9).fillColor('#475569').font('Helvetica')
          .text(p.notes, 64, bottomY + 24, { width: pageWidth - 28 });
      }

      // ── FOOTER ──
      const footerText = c?.footerText || 'Generated by StockMate Pro';
      doc.fontSize(8).fillColor(grayColor).font('Helvetica')
        .text(
          `${footerText} | This is a computer-generated document.`,
          50, doc.page.height - 70,
          { align: 'center', width: pageWidth }
        );

      doc.fontSize(7).fillColor('#94a3b8')
        .text(
          new Date().toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }),
          50, doc.page.height - 55,
          { align: 'center', width: pageWidth }
        );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate a sale invoice PDF as a Buffer
 * @param {Object} sale - Full sale object with items, customer, branch, user
 * @param {Object} [company] - Optional company profile with name, address, phone, email, gstNumber, logoUrl, footerText
 * @returns {Promise<Buffer>}
 */
const generateInvoicePDF = async (sale, company = null) => {
  const s = sale;
  const c = company;

  // Fetch logo upfront if available
  let logoBuffer = null;
  if (c?.logoUrl) {
    try {
      const protocol = c.logoUrl.startsWith('https') ? https : http;
      logoBuffer = await new Promise((resolve, reject) => {
        protocol.get(c.logoUrl, (res) => {
          const chunks = [];
          res.on('data', (chunk) => chunks.push(chunk));
          res.on('end', () => resolve(Buffer.concat(chunks)));
          res.on('error', reject);
        }).on('error', reject);
      });
    } catch (e) {
      // Logo fetch failed, continue without logo
    }
  }

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
        info: {
          Title: `Invoice - ${s.invoiceNo}`,
          Author: c?.companyName || 'StockMate Pro',
          Subject: `Invoice #${s.invoiceNo}`,
        },
      });

      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const pageWidth = doc.page.width - 100;
      const primaryColor = '#059669';
      const grayColor = '#64748b';
      const lightGray = '#f1f5f9';
      const borderColor = '#e2e8f0';

      // ── Helper functions ──
      const formatPrice = (paise) => {
        if (paise == null) return '₹0.00';
        return `₹${(paise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
      };

      const formatShortDate = (d) => {
        if (!d) return '—';
        return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
      };

      // ── HEADER: Company & Invoice Info ──
      const companyName = c?.companyName || s.branch?.name || 'StockMate Pro';

      let headerX = 50;
      let headerNameX = 50;
      if (logoBuffer) {
        doc.image(logoBuffer, 50, 50, { width: 50, height: 50 });
        headerNameX = 115;
      }
      doc.fontSize(20).fillColor(primaryColor).font('Helvetica-Bold')
        .text(companyName, headerNameX, 50);

      const companyAddr = [
        c?.address || s.branch?.address,
        c?.phone || s.branch?.phone,
        (c?.gstNumber || s.branch?.gstNumber) ? `GST: ${c?.gstNumber || s.branch?.gstNumber}` : '',
      ].filter(Boolean).join('\n');
      if (companyAddr) {
        const addrY = logoBuffer ? 82 : 78;
        const addrX = logoBuffer ? headerNameX : 50;
        doc.fontSize(9).fillColor(grayColor).font('Helvetica')
          .text(companyAddr, addrX, addrY, { width: 250 });
      }

      // Invoice number - Right aligned
      doc.fontSize(16).fillColor('#1e293b').font('Helvetica-Bold')
        .text('TAX INVOICE', 0, 50, { align: 'right', width: doc.page.width - 50 });

      doc.fontSize(22).fillColor('#1e293b').font('Helvetica-Bold')
        .text(s.invoiceNo, 0, 70, { align: 'right', width: doc.page.width - 50 });

      // Status badge
      const statusColors = {
        PAID: '#059669', PARTIAL: '#d97706', PENDING: '#64748b',
        OVERDUE: '#dc2626', CANCELLED: '#94a3b8',
      };
      const statusColor = statusColors[s.paymentStatus] || '#64748b';
      doc.fontSize(10).fillColor(statusColor).font('Helvetica-Bold')
        .text(s.paymentStatus, 0, 96, { align: 'right', width: doc.page.width - 50 });

      // Date right side
      doc.fontSize(9).fillColor(grayColor).font('Helvetica')
        .text(`Date: ${formatShortDate(s.createdAt)}`, 0, 112, { align: 'right', width: doc.page.width - 50 });

      if (s.isReturn) {
        doc.fillColor('#7c3aed').text('Return Invoice', 0, 126, { align: 'right', width: doc.page.width - 50 });
      }

      // Divider
      doc.moveTo(50, 145).lineTo(doc.page.width - 50, 145).strokeColor(primaryColor).lineWidth(2).stroke();

      // ── INFO SECTION: Customer & Payment ──
      const infoY = 160;

      // Customer box
      doc.roundedRect(50, infoY, pageWidth / 2 - 12, 82, 6).fillColor('#f8fafc').fill()
        .roundedRect(50, infoY, pageWidth / 2 - 12, 82, 6).strokeColor(borderColor).lineWidth(1).stroke();

      doc.fontSize(9).fillColor(grayColor).font('Helvetica-Bold')
        .text('CUSTOMER', 64, infoY + 8);

      if (s.customer) {
        doc.fontSize(10).fillColor('#334155').font('Helvetica-Bold')
          .text(s.customer.name, 64, infoY + 24);
        const customerInfo = [
          s.customer.phone ? `Phone: ${s.customer.phone}` : '',
          s.customer.email ? `Email: ${s.customer.email}` : '',
          s.customer.address,
          s.customer.gstNumber ? `GST: ${s.customer.gstNumber}` : '',
        ].filter(Boolean).join('\n');
        doc.fontSize(9).fillColor('#475569').font('Helvetica')
          .text(customerInfo, 64, infoY + 42, { width: pageWidth / 2 - 36 });
      } else {
        doc.fontSize(10).fillColor(grayColor).font('Helvetica').text('Walk-in Customer', 64, infoY + 24);
      }

      // Payment box
      doc.roundedRect(50 + pageWidth / 2 + 12, infoY, pageWidth / 2 - 12, 82, 6).fillColor('#f8fafc').fill()
        .roundedRect(50 + pageWidth / 2 + 12, infoY, pageWidth / 2 - 12, 82, 6).strokeColor(borderColor).lineWidth(1).stroke();

      doc.fontSize(9).fillColor(grayColor).font('Helvetica-Bold')
        .text('PAYMENT', 64 + pageWidth / 2 + 12, infoY + 8);

      const payX = 64 + pageWidth / 2 + 12;
      const payMethod = (s.paymentMethod || 'CASH')
        .replace(/_/g, ' ')
        .replace(/\b\w/g, (l) => l.toUpperCase());

      doc.fontSize(9).fillColor('#475569').font('Helvetica')
        .text(`Method: ${payMethod}`, payX, infoY + 26)
        .text(`Status: ${s.paymentStatus}${s.paymentStatus === 'PAID' ? ' ✓' : ''}`, payX, infoY + 40)
        .text(`Paid: ${formatPrice(s.paidAmount)}`, payX, infoY + 54);

      if (s.balanceAmount > 0) {
        doc.fillColor('#d97706').text(`Balance: ${formatPrice(s.balanceAmount)}`, payX, infoY + 68);
      } else {
        doc.fillColor('#059669').text('Fully Paid', payX, infoY + 68);
      }

      // ── ITEMS TABLE ──
      const tableTop = infoY + 100;
      const colWidths = [30, 170, 44, 82, 48, 90];
      const headers = ['#', 'Item', 'Qty', 'Rate', 'GST', 'Total'];

      // Table header bg
      doc.rect(50, tableTop, pageWidth, 24).fill(lightGray);

      let x = 50;
      doc.fontSize(8).fillColor(grayColor).font('Helvetica-Bold');
      headers.forEach((h, i) => {
        const align = i === 0 || i === 2 || i === 4 ? 'center' : 'right';
        doc.text(h, x, tableTop + 6, { width: colWidths[i], align, lineBreak: false });
        x += colWidths[i];
      });

      // Table rows
      let rowY = tableTop + 24;
      const items = s.items || [];

      items.forEach((item, idx) => {
        const gstPercent = parseInt((item.gstRate || 'RATE_18').replace('RATE_', ''));
        const total = item.totalPrice || (item.unitPrice * item.quantity - (item.discount || 0) + (item.gstAmount || 0));

        // Row background (alternating)
        if (idx % 2 === 0) {
          doc.rect(50, rowY, pageWidth, 22).fill('#fafafa');
        }

        // Row bottom border
        doc.moveTo(50, rowY + 22).lineTo(doc.page.width - 50, rowY + 22).strokeColor(borderColor).lineWidth(0.5).stroke();

        // Row data
        const cells = [
          String(idx + 1),
          item.item?.name || 'Item',
          String(item.quantity),
          formatPrice(item.unitPrice),
          `${gstPercent}%`,
          formatPrice(total),
        ];

        let cx = 50;
        doc.fontSize(9).fillColor('#334155').font('Helvetica');
        cells.forEach((cell, i) => {
          const align = i === 0 || i === 2 || i === 4 ? 'center' : i === 3 || i === 5 ? 'right' : 'left';
          const font = i === 5 ? 'Helvetica-Bold' : 'Helvetica';
          doc.font(font).text(cell, cx, rowY + 4, { width: colWidths[i], align, lineBreak: false });
          cx += colWidths[i];
        });

        // SKU under item name
        if (item.item?.sku) {
          doc.fontSize(7).fillColor(grayColor).font('Helvetica')
            .text(item.item.sku, 80, rowY + 12, { width: 140 });
        }

        rowY += 22;
      });

      // ── TOTALS ──
      const totalsX = doc.page.width - 50 - 240;
      const totalsY = rowY + 10;

      const totalsData = [
        { label: 'Subtotal', value: formatPrice(s.subtotal), color: '#334155', bold: false },
        ...(s.discountTotal > 0
          ? [{ label: 'Discount', value: `−${formatPrice(s.discountTotal)}`, color: '#dc2626', bold: false }]
          : []),
        { label: 'GST Total', value: formatPrice(s.gstTotal), color: '#334155', bold: false },
        { label: 'Grand Total', value: formatPrice(s.grandTotal), color: '#ffffff', bold: true, isGrand: true },
      ];

      if (s.balanceAmount > 0) {
        totalsData.push({ label: 'Balance Due', value: formatPrice(s.balanceAmount), color: '#d97706', bold: true });
      }

      totalsData.forEach((row) => {
        if (row.isGrand) {
          doc.rect(totalsX, totalsY, 240, 26).fill(primaryColor);
        }
        doc.fontSize(row.isGrand ? 11 : 9)
          .fillColor(row.color)
          .font(row.bold ? 'Helvetica-Bold' : 'Helvetica');
        doc.text(row.label, totalsX + 12, totalsY + (row.isGrand ? 6 : 3), { width: 120 });
        doc.text(row.value, totalsX + 132, totalsY + (row.isGrand ? 6 : 3), { width: 96, align: 'right' });
        if (!row.isGrand) {
          doc.moveTo(totalsX, totalsY + 20).lineTo(totalsX + 240, totalsY + 20).strokeColor(borderColor).lineWidth(0.5).stroke();
        }
      });

      // ── NOTES ──
      let bottomY = totalsY + (totalsData.length * 22) + 20;

      if (s.notes) {
        doc.roundedRect(50, bottomY, pageWidth, 50, 6).fillColor('#f8fafc').fill()
          .roundedRect(50, bottomY, pageWidth, 50, 6).strokeColor(borderColor).lineWidth(1).stroke();
        doc.fontSize(9).fillColor(grayColor).font('Helvetica-Bold')
          .text('NOTES', 64, bottomY + 8);
        doc.fontSize(9).fillColor('#475569').font('Helvetica')
          .text(s.notes, 64, bottomY + 24, { width: pageWidth - 28 });
      }

      // ── FOOTER ──
      const footerText = c?.footerText || 'Thank you for your business!';
      doc.fontSize(8).fillColor(grayColor).font('Helvetica')
        .text(
          `${footerText} | This is a computer-generated invoice.`,
          50, doc.page.height - 70,
          { align: 'center', width: pageWidth }
        );

      doc.fontSize(7).fillColor('#94a3b8')
        .text(
          new Date().toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }),
          50, doc.page.height - 55,
          { align: 'center', width: pageWidth }
        );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate an inventory item label/details PDF as a Buffer
 * @param {Object} item - Full inventory item with stockMovements, suppliers
 * @param {Object} [company]
 * @returns {Promise<Buffer>}
 */
const generateItemPDF = async (item, company = null) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      addHeader(doc, company, `Item Details: ${item.name}`);

      let y = 120;
      const pageWidth = doc.page.width - 100;
      const leftX = 50;
      const rightX = doc.page.width / 2 + 10;

      // QR Code block
      doc.fontSize(14).fillColor('#6366f1').font('Helvetica-Bold')
        .text('ITEM INFORMATION', leftX, y);
      y += 24;

      // Left column
      const leftItems = [
        ['SKU', item.sku],
        ['Name', item.name],
        ['Category', item.category],
        ['Brand', item.brand || '—'],
        ['Model', item.model || '—'],
        ['Barcode', item.barcode || '—'],
        ['Location', item.location || '—'],
        ['Unit Type', item.unitType || 'PCS'],
      ];

      doc.fontSize(9).fillColor('#64748b').font('Helvetica-Bold');
      leftItems.forEach(([label, val]) => {
        doc.text(label, leftX, y, { width: 100 });
        doc.fillColor('#334155').font('Helvetica').text(String(val), leftX + 100, y, { width: 180 });
        doc.fillColor('#64748b').font('Helvetica-Bold');
        y += 16;
      });

      // Right column - stock & pricing
      y = 144;
      const rightItems = [
        ['Current Stock', String(item.currentStock)],
        ['Min Stock', String(item.minStock)],
        ['Max Stock', String(item.maxStock)],
        ['Purchase Price', formatPrice(item.purchasePrice)],
        ['Selling Price', formatPrice(item.sellingPrice)],
        ['GST Rate', `${item.gstRate ? item.gstRate.replace('RATE_', '') : '18'}%`],
        ['Expiry Date', formatShortDate(item.expiryDate)],
        ['Warranty', item.warrantyMonths ? `${item.warrantyMonths} months` : '—'],
      ];

      doc.fontSize(9).fillColor('#64748b').font('Helvetica-Bold');
      rightItems.forEach(([label, val]) => {
        doc.text(label, rightX, y, { width: 100 });
        doc.fillColor('#334155').font('Helvetica').text(String(val), rightX + 100, y, { width: 180 });
        doc.fillColor('#64748b').font('Helvetica-Bold');
        y += 16;
      });

      // Description
      y = Math.max(y + 10, 310);
      if (item.description) {
        doc.roundedRect(leftX, y, pageWidth, 50, 6).fillColor('#f8fafc').fill()
          .roundedRect(leftX, y, pageWidth, 50, 6).strokeColor('#e2e8f0').lineWidth(1).stroke();
        doc.fontSize(9).fillColor('#64748b').font('Helvetica-Bold')
          .text('DESCRIPTION', leftX + 12, y + 8);
        doc.fontSize(9).fillColor('#475569').font('Helvetica')
          .text(item.description, leftX + 12, y + 26, { width: pageWidth - 24 });
        y += 60;
      }

      // Suppliers
      if (item.suppliers?.length > 0) {
        y += 10;
        doc.fontSize(10).fillColor('#6366f1').font('Helvetica-Bold')
          .text('SUPPLIERS', leftX, y);
        y += 18;
        item.suppliers.forEach((is) => {
          if (is.supplier) {
            doc.fontSize(9).fillColor('#334155').font('Helvetica')
              .text(`• ${is.supplier.name}`, leftX + 5, y);
            y += 14;
          }
        });
      }

      // Recent stock movements
      if (item.stockMovements?.length > 0) {
        y += 10;
        doc.fontSize(10).fillColor('#6366f1').font('Helvetica-Bold')
          .text('RECENT STOCK MOVEMENTS', leftX, y);
        y += 20;

        const moveHeaders = ['Date', 'Type', 'Qty', 'Reason'];
        const moveCols = [80, 60, 50, 270];
        let mx = leftX;
        doc.fontSize(8).fillColor('#64748b').font('Helvetica-Bold');
        moveHeaders.forEach((h, i) => {
          doc.text(h, mx, y, { width: moveCols[i], align: i === 2 ? 'center' : 'left', lineBreak: false });
          mx += moveCols[i];
        });
        y += 16;

        item.stockMovements.slice(0, 10).forEach((mov) => {
          mx = leftX;
          doc.fontSize(8).fillColor('#475569').font('Helvetica');
          [formatShortDate(mov.createdAt), mov.type, String(mov.quantity), mov.reason || '—'].forEach((val, i) => {
            doc.text(val, mx, y, { width: moveCols[i], align: i === 2 ? 'center' : 'left', lineBreak: false });
            mx += moveCols[i];
          });
          y += 13;
        });
      }

      addFooter(doc);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate a supplier profile PDF as a Buffer
 */
const generateSupplierPDF = async (supplier, company = null) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      addHeader(doc, company, `Supplier Profile: ${supplier.name}`);

      let y = 120;
      const leftX = 50;
      const rightX = doc.page.width / 2 + 10;
      const pageWidth = doc.page.width - 100;

      const leftInfo = [
        ['Name', supplier.name],
        ['GST Number', supplier.gstNumber || '—'],
        ['Contact Person', supplier.contactPerson || '—'],
        ['Phone', supplier.phone || '—'],
        ['Email', supplier.email || '—'],
      ];

      doc.fontSize(9).fillColor('#64748b').font('Helvetica-Bold');
      leftInfo.forEach(([label, val]) => {
        doc.text(label, leftX, y, { width: 100 });
        doc.fillColor('#334155').font('Helvetica').text(String(val), leftX + 100, y, { width: 180 });
        doc.fillColor('#64748b').font('Helvetica-Bold');
        y += 16;
      });

      y = 120;
      const rightInfo = [
        ['Address', supplier.address || '—'],
        ['City', supplier.city || '—'],
        ['State', supplier.state || '—'],
        ['Pincode', supplier.pincode || '—'],
        ['Outstanding', formatPrice(supplier.outstanding)],
      ];

      doc.fontSize(9).fillColor('#64748b').font('Helvetica-Bold');
      rightInfo.forEach(([label, val]) => {
        doc.text(label, rightX, y, { width: 100 });
        doc.fillColor('#334155').font('Helvetica').text(String(val), rightX + 100, y, { width: 180 });
        doc.fillColor('#64748b').font('Helvetica-Bold');
        y += 16;
      });

      // Bank details
      if (supplier.bankName || supplier.bankAccount) {
        y = Math.max(y + 10, 280);
        doc.roundedRect(leftX, y, pageWidth, 70, 6).fillColor('#f8fafc').fill()
          .roundedRect(leftX, y, pageWidth, 70, 6).strokeColor('#e2e8f0').lineWidth(1).stroke();
        doc.fontSize(9).fillColor('#64748b').font('Helvetica-Bold')
          .text('BANK DETAILS', leftX + 12, y + 8);
        doc.fontSize(9).fillColor('#475569').font('Helvetica')
          .text(`Bank: ${supplier.bankName || '—'}`, leftX + 12, y + 26, { width: pageWidth - 24 })
          .text(`Account: ${supplier.bankAccount || '—'}`, leftX + 12, y + 40, { width: pageWidth - 24 })
          .text(`IFSC: ${supplier.bankIfsc || '—'}`, leftX + 12, y + 54, { width: pageWidth - 24 });
        y += 80;
      }

      // Recent purchases
      if (supplier.purchases?.length > 0) {
        y += 10;
        doc.fontSize(10).fillColor('#2563eb').font('Helvetica-Bold')
          .text('RECENT PURCHASES', leftX, y);
        y += 20;

        const pHeaders = ['PO No', 'Date', 'Status', 'Total', 'Payment'];
        const pCols = [120, 90, 80, 100, 100];
        let px = leftX;
        doc.fontSize(8).fillColor('#64748b').font('Helvetica-Bold');
        pHeaders.forEach((h, i) => {
          doc.text(h, px, y, { width: pCols[i], align: i >= 3 ? 'right' : 'left', lineBreak: false });
          px += pCols[i];
        });
        y += 16;

        supplier.purchases.slice(0, 10).forEach((p) => {
          px = leftX;
          doc.fontSize(8).fillColor('#475569').font('Helvetica');
          [p.poNumber, formatShortDate(p.orderDate), p.status, formatPrice(p.grandTotal), p.paymentStatus].forEach((val, i) => {
            doc.text(val, px, y, { width: pCols[i], align: i >= 3 ? 'right' : 'left', lineBreak: false });
            px += pCols[i];
          });
          y += 13;
        });
      }

      addFooter(doc);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate a customer profile PDF as a Buffer
 */
const generateCustomerPDF = async (customer, company = null) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      addHeader(doc, company, `Customer Profile: ${customer.name}`);

      let y = 120;
      const leftX = 50;
      const rightX = doc.page.width / 2 + 10;
      const pageWidth = doc.page.width - 100;

      const leftInfo = [
        ['Name', customer.name],
        ['Phone', customer.phone || '—'],
        ['Email', customer.email || '—'],
        ['GST Number', customer.gstNumber || '—'],
      ];

      doc.fontSize(9).fillColor('#64748b').font('Helvetica-Bold');
      leftInfo.forEach(([label, val]) => {
        doc.text(label, leftX, y, { width: 100 });
        doc.fillColor('#334155').font('Helvetica').text(String(val), leftX + 100, y, { width: 180 });
        doc.fillColor('#64748b').font('Helvetica-Bold');
        y += 16;
      });

      y = 120;
      const rightInfo = [
        ['Address', customer.address || '—'],
        ['City', customer.city || '—'],
        ['State', customer.state || '—'],
        ['Outstanding', formatPrice(customer.outstanding)],
      ];

      doc.fontSize(9).fillColor('#64748b').font('Helvetica-Bold');
      rightInfo.forEach(([label, val]) => {
        doc.text(label, rightX, y, { width: 100 });
        doc.fillColor('#334155').font('Helvetica').text(String(val), rightX + 100, y, { width: 180 });
        doc.fillColor('#64748b').font('Helvetica-Bold');
        y += 16;
      });

      // Recent sales
      if (customer.sales?.length > 0) {
        y = Math.max(y + 10, 260);
        doc.fontSize(10).fillColor('#059669').font('Helvetica-Bold')
          .text('RECENT SALES', leftX, y);
        y += 20;

        const sHeaders = ['Invoice', 'Date', 'Items', 'Total', 'Payment'];
        const sCols = [120, 90, 60, 100, 110];
        let sx = leftX;
        doc.fontSize(8).fillColor('#64748b').font('Helvetica-Bold');
        sHeaders.forEach((h, i) => {
          doc.text(h, sx, y, { width: sCols[i], align: i >= 3 ? 'right' : 'left', lineBreak: false });
          sx += sCols[i];
        });
        y += 16;

        customer.sales.slice(0, 10).forEach((s) => {
          sx = leftX;
          doc.fontSize(8).fillColor('#475569').font('Helvetica');
          [s.invoiceNo, formatShortDate(s.createdAt), String(s.items?.length || 0), formatPrice(s.grandTotal), s.paymentStatus].forEach((val, i) => {
            doc.text(val, sx, y, { width: sCols[i], align: i >= 3 ? 'right' : 'left', lineBreak: false });
            sx += sCols[i];
          });
          y += 13;
        });
      }

      addFooter(doc);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate an expense receipt PDF as a Buffer
 */
const generateExpensePDF = async (expense, company = null) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      addHeader(doc, company, 'Expense Receipt');

      let y = 130;
      const leftX = 50;
      const pageWidth = doc.page.width - 100;

      const fields = [
        ['Category', expense.category],
        ['Amount', formatPrice(expense.amount)],
        ['Date', formatShortDate(expense.date)],
        ['Description', expense.description || '—'],
        ['Recorded By', expense.user ? `${expense.user.firstName} ${expense.user.lastName}` : '—'],
      ];

      doc.fontSize(9).fillColor('#64748b').font('Helvetica-Bold');
      fields.forEach(([label, val]) => {
        doc.roundedRect(leftX, y, pageWidth, 24, 4).fillColor('#f8fafc').fill()
          .roundedRect(leftX, y, pageWidth, 24, 4).strokeColor('#e2e8f0').lineWidth(0.5).stroke();
        doc.text(label, leftX + 12, y + 6, { width: 100 });
        doc.fillColor('#334155').font('Helvetica').text(String(val), leftX + 120, y + 6, { width: pageWidth - 140 });
        doc.fillColor('#64748b').font('Helvetica-Bold');
        y += 28;
      });

      addFooter(doc);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate an inventory list (bulk) PDF as a Buffer
 * @param {Array} items - Array of inventory items
 * @param {Object} [company]
 * @returns {Promise<Buffer>}
 */
const generateInventoryListPDF = async (items, company = null) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      addHeader(doc, company, 'Inventory List');

      let y = 120;
      const pageWidth = doc.page.width - 100;
      const leftX = 50;

      // Summary
      doc.fontSize(9).fillColor('#64748b').font('Helvetica')
        .text(`Total Items: ${items.length} • ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}`, leftX, y);
      y += 20;

      // Table header
      const colWidths = [28, 150, 60, 52, 52, 68, 68, 60];
      const headers = ['#', 'Item', 'Category', 'SKU', 'Stock', 'Purchase', 'Selling', 'Status'];

      doc.rect(leftX, y, pageWidth, 22).fill('#f1f5f9');
      let hx = leftX;
      doc.fontSize(7.5).fillColor('#475569').font('Helvetica-Bold');
      headers.forEach((h, i) => {
        const align = i === 0 ? 'center' : (i >= 4 ? 'right' : 'left');
        doc.text(h, hx, y + 4, { width: colWidths[i], align, lineBreak: false });
        hx += colWidths[i];
      });
      y += 22;

      // Table rows
      items.forEach((item, idx) => {
        if (y > 750) {
          doc.addPage();
          y = 50;
          // Re-draw header on new page
          doc.rect(leftX, y, pageWidth, 22).fill('#f1f5f9');
          hx = leftX;
          doc.fontSize(7.5).fillColor('#475569').font('Helvetica-Bold');
          headers.forEach((h, i) => {
            const align = i === 0 ? 'center' : (i >= 4 ? 'right' : 'left');
            doc.text(h, hx, y + 4, { width: colWidths[i], align, lineBreak: false });
            hx += colWidths[i];
          });
          y += 22;
        }

        if (idx % 2 === 0) {
          doc.rect(leftX, y, pageWidth, 20).fill('#fafafa');
        }
        doc.moveTo(leftX, y + 20).lineTo(doc.page.width - 50, y + 20).strokeColor('#e2e8f0').lineWidth(0.5).stroke();

        const isLow = item.currentStock <= item.minStock;
        const cells = [
          String(idx + 1),
          item.name,
          item.category || '—',
          item.sku || '—',
          String(item.currentStock),
          formatPrice(item.purchasePrice),
          formatPrice(item.sellingPrice),
          isLow ? 'Low' : (item.isActive === false ? 'Inactive' : 'Active'),
        ];

        let cx = leftX;
        doc.fontSize(8).fillColor('#334155').font('Helvetica');
        cells.forEach((cell, i) => {
          const align = i === 0 ? 'center' : (i >= 4 ? 'right' : 'left');
          const color = i === 4 && isLow ? '#d97706' : '#334155';
          doc.fillColor(color).text(cell, cx, y + 3, { width: colWidths[i], align, lineBreak: false });
          cx += colWidths[i];
        });
        doc.fillColor('#334155');
        y += 20;
      });

      // Totals row
      y += 5;
      const totalValue = items.reduce((s, i) => s + (i.currentStock || 0) * (i.sellingPrice || 0), 0);
      const lowCount = items.filter(i => i.currentStock <= i.minStock).length;
      doc.rect(leftX, y, pageWidth, 22).fill('#f1f5f9');
      doc.fontSize(8).fillColor('#1e293b').font('Helvetica-Bold')
        .text(`Total Items: ${items.length}`, leftX + 8, y + 5)
        .text(`Low Stock: ${lowCount}`, leftX + 140, y + 5)
        .text(`Inventory Value: ${formatPrice(totalValue)}`, leftX + 280, y + 5,
          { width: pageWidth - 290, align: 'right' });

      addFooter(doc);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Generate a supplier list (bulk) PDF as a Buffer
 * @param {Array} suppliers - Array of supplier objects
 * @param {Object} [company]
 * @returns {Promise<Buffer>}
 */
const generateSupplierListPDF = async (suppliers, company = null) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      addHeader(doc, company, 'Supplier List');

      let y = 120;
      const pageWidth = doc.page.width - 100;
      const leftX = 50;

      const totalOutstanding = suppliers.reduce((s, sup) => s + (sup.outstanding || 0), 0);
      const activeCount = suppliers.filter(s => s.isActive !== false).length;

      doc.fontSize(9).fillColor('#64748b').font('Helvetica')
        .text(
          `Total: ${suppliers.length} • Active: ${activeCount} • Outstanding: ${formatPrice(totalOutstanding)}`,
          leftX, y
        );
      y += 20;

      // Table header
      const colWidths = [28, 155, 95, 80, 72, 62, 54];
      const headers = ['#', 'Name', 'Contact Person', 'Phone', 'Email', 'Outstanding', 'Status'];

      doc.rect(leftX, y, pageWidth, 22).fill('#f1f5f9');
      let hx = leftX;
      doc.fontSize(7.5).fillColor('#475569').font('Helvetica-Bold');
      headers.forEach((h, i) => {
        const align = i === 0 ? 'center' : (i >= 4 ? 'right' : 'left');
        doc.text(h, hx, y + 4, { width: colWidths[i], align, lineBreak: false });
        hx += colWidths[i];
      });
      y += 22;

      // Table rows
      suppliers.forEach((sup, idx) => {
        if (y > 750) {
          doc.addPage();
          y = 50;
          doc.rect(leftX, y, pageWidth, 22).fill('#f1f5f9');
          hx = leftX;
          doc.fontSize(7.5).fillColor('#475569').font('Helvetica-Bold');
          headers.forEach((h, i) => {
            const align = i === 0 ? 'center' : (i >= 4 ? 'right' : 'left');
            doc.text(h, hx, y + 4, { width: colWidths[i], align, lineBreak: false });
            hx += colWidths[i];
          });
          y += 22;
        }

        if (idx % 2 === 0) {
          doc.rect(leftX, y, pageWidth, 20).fill('#fafafa');
        }
        doc.moveTo(leftX, y + 20).lineTo(doc.page.width - 50, y + 20).strokeColor('#e2e8f0').lineWidth(0.5).stroke();

        const cells = [
          String(idx + 1),
          sup.name,
          sup.contactPerson || '—',
          sup.phone || '—',
          sup.email || '—',
          formatPrice(sup.outstanding),
          sup.isActive !== false ? 'Active' : 'Inactive',
        ];

        let cx = leftX;
        doc.fontSize(8).fillColor('#334155').font('Helvetica');
        cells.forEach((cell, i) => {
          const align = i === 0 ? 'center' : (i >= 4 ? 'right' : 'left');
          const color = i === 5 && sup.outstanding > 0 ? '#d97706' : '#334155';
          doc.fillColor(color).text(cell, cx, y + 3, { width: colWidths[i], align, lineBreak: false });
          cx += colWidths[i];
        });
        doc.fillColor('#334155');
        y += 20;
      });

      addFooter(doc);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generatePOPDF, generateInvoicePDF, generateItemPDF, generateSupplierPDF, generateCustomerPDF, generateExpensePDF, generateInventoryListPDF, generateSupplierListPDF };
